---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rpk-api
  namespace: rpk-api
spec:
  dnsNames:
  - api.rampike.de
  issuerRef:
    kind: ClusterIssuer
    name: acme-staging
  secretName: rpk-api-certificate
