---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: rpk-api
  namespace: rpk-api
  labels:
    app: rpk-api
spec:
  minReadySeconds: 3
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: rpk-api
  template:
    metadata:
      labels:
        app: rpk-api
    spec:
      containers:
      - name: rpk-api
        image: rampike/rpk-api:0.0.2
        imagePullPolicy: IfNotPresent
        ports:
        - name: web
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /v0/healthz
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /v0/readyz
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi
