apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress-route.yaml
- certificate.yaml
- hpa.yaml
images:
- name: rampike/rpk-api
  newName: rampike/rpk-api
  newTag: 0.0.9
